version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

executors:
  default:
    docker:
      - image: circleci/ruby:2.7

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Bundle
          command: gem install bundler
      - run:
          name: Install awspec
          command: bundle install --path vendor/bundle
      - run:
          name: exec awspec (wip)
          command: bundle exec rake spec
  infratest:
    executor: default
    environment:
      # - AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # - AWS_REGION: ${AWS_REGION}
      # - AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    steps:
      - run:
          name: infra test - vpc
          command: echo hi
      # - run:
      #     name: check vpc
      #     command: bundle exec rake spec
workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build
      - infratest:
          requires:
            - build
