version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

executors:
  working_directory: ~/workspace
  default:
    docker:
      - image: circleci/ruby:2.7

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach-workspace:
    steps:
      - attach_workspace:
          at: .
  bundle-install:
    steps:
      - run:
          name: Install Bundle
          command: gem install bundler
      - run:
          name: install gems
          command: bundle install --path vendor/bundle
  test-vpc:
    steps:
      - run:
          name: infra test - vpc
          command: bundle exec rake spec

jobs:
  build:
    executor: default
    steps:
      - checkout
      - bundle-install
      - persist-workspace

  infratest:
    executor: default
    environment:
      # - AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      # - AWS_REGION: ${AWS_REGION}
      # - AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    steps:
      - attach-workspace
      - bundle-install
      - test-vpc
      # - run:
      #     name: check vpc
      #     command: bundle exec rake spec
workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build
      - infratest:
          requires:
            - build
