version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
  infratest:
    docker:
      - image: circleci/ruby:2.7
    environment:
      - AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      - AWS_REGION: $AWS_REGION
      - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
    steps:
      - checkout

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - build
      - infratest:
          requires:
            - build
