version: 2.1

executors:
  working_directory: ~/workspace
  default:
    docker:
      - image: circleci/ruby:2.7

commands:
  persist-workspace:
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
  attach-workspace:
    steps:
      - attach_workspace:
          at: .
  bundle-install:
    steps:
      - run:
          name: Install Bundle
          command: gem install bundler
      - restore_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: install gems
          command: bundle install --path vendor/bundle
      - save_cache:
          key: bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  test-vpc:
    steps:
      - run:
          name: infra test - vpc
          command: bundle exec rake spec

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - persist-workspace

  infra-test:
    executor: default
    steps:
      - attach-workspace
      - bundle-install
      - test-vpc

workflows:
  version: 2
  build_and_test_workflow:
    jobs:
      - setup
      - infra-test:
          requires:
            - setup
